package gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Alisoft
 */
public class PrincipalGUI extends javax.swing.JFrame {

    gui.itemPanel itemPanels[];

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
        AtributosGUI.setColoresEstandar();
        codigoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpaneFondo = new javax.swing.JPanel();
        jpaneMenu = new javax.swing.JPanel();
        jpaneMenuItems = new javax.swing.JPanel();
        jpanePerfil = new javax.swing.JPanel();
        jlblPerfil = new javax.swing.JLabel();
        jpaneActivePerfil = new javax.swing.JPanel();
        jpaneHorario = new javax.swing.JPanel();
        jpaneActiveHorario = new javax.swing.JPanel();
        jlblHorario = new javax.swing.JLabel();
        jpaneTramites = new javax.swing.JPanel();
        jpaneActiveTramites = new javax.swing.JPanel();
        jlblTramites = new javax.swing.JLabel();
        jpaneCursos = new javax.swing.JPanel();
        jpaneActiveCursos = new javax.swing.JPanel();
        jlblCursos = new javax.swing.JLabel();
        jpaneSalud = new javax.swing.JPanel();
        jpaneActiveSalud = new javax.swing.JPanel();
        jlblSalud = new javax.swing.JLabel();
        jpanePrincipal = new javax.swing.JPanel();
        jscrollpanePaneles = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpaneMenu.setBackground(new java.awt.Color(51, 153, 255));
        jpaneMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpaneMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpaneMenuMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jpaneMenuMouseReleased(evt);
            }
        });

        jpaneMenuItems.setBackground(new java.awt.Color(51, 153, 255));

        jpanePerfil.setBackground(new java.awt.Color(51, 146, 248));
        jpanePerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpanePerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpanePerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpanePerfilMouseExited(evt);
            }
        });

        jlblPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jlblPerfil.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jlblPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jlblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/white-user-materialdesign-35px.png"))); // NOI18N
        jlblPerfil.setText("   Mi Perfil");

        jpaneActivePerfil.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpaneActivePerfilLayout = new javax.swing.GroupLayout(jpaneActivePerfil);
        jpaneActivePerfil.setLayout(jpaneActivePerfilLayout);
        jpaneActivePerfilLayout.setHorizontalGroup(
            jpaneActivePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpaneActivePerfilLayout.setVerticalGroup(
            jpaneActivePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanePerfilLayout = new javax.swing.GroupLayout(jpanePerfil);
        jpanePerfil.setLayout(jpanePerfilLayout);
        jpanePerfilLayout.setHorizontalGroup(
            jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanePerfilLayout.createSequentialGroup()
                .addComponent(jpaneActivePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanePerfilLayout.setVerticalGroup(
            jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanePerfilLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpanePerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpaneActivePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpaneHorario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpaneHorarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpaneHorarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpaneHorarioMouseExited(evt);
            }
        });

        jpaneActiveHorario.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpaneActiveHorarioLayout = new javax.swing.GroupLayout(jpaneActiveHorario);
        jpaneActiveHorario.setLayout(jpaneActiveHorarioLayout);
        jpaneActiveHorarioLayout.setHorizontalGroup(
            jpaneActiveHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpaneActiveHorarioLayout.setVerticalGroup(
            jpaneActiveHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jlblHorario.setBackground(new java.awt.Color(255, 255, 255));
        jlblHorario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblHorario.setForeground(new java.awt.Color(255, 255, 255));
        jlblHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tabla-materialdesign-35px.png"))); // NOI18N
        jlblHorario.setText("   Mis Horarios");

        javax.swing.GroupLayout jpaneHorarioLayout = new javax.swing.GroupLayout(jpaneHorario);
        jpaneHorario.setLayout(jpaneHorarioLayout);
        jpaneHorarioLayout.setHorizontalGroup(
            jpaneHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneHorarioLayout.createSequentialGroup()
                .addComponent(jpaneActiveHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpaneHorarioLayout.setVerticalGroup(
            jpaneHorarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneActiveHorario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jpaneTramites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpaneTramitesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpaneTramitesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpaneTramitesMouseExited(evt);
            }
        });

        jpaneActiveTramites.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpaneActiveTramitesLayout = new javax.swing.GroupLayout(jpaneActiveTramites);
        jpaneActiveTramites.setLayout(jpaneActiveTramitesLayout);
        jpaneActiveTramitesLayout.setHorizontalGroup(
            jpaneActiveTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpaneActiveTramitesLayout.setVerticalGroup(
            jpaneActiveTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jlblTramites.setBackground(new java.awt.Color(255, 255, 255));
        jlblTramites.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tramite-materialdesign-35px.png"))); // NOI18N
        jlblTramites.setText("   Mis Trámites");

        javax.swing.GroupLayout jpaneTramitesLayout = new javax.swing.GroupLayout(jpaneTramites);
        jpaneTramites.setLayout(jpaneTramitesLayout);
        jpaneTramitesLayout.setHorizontalGroup(
            jpaneTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneTramitesLayout.createSequentialGroup()
                .addComponent(jpaneActiveTramites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblTramites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpaneTramitesLayout.setVerticalGroup(
            jpaneTramitesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneActiveTramites, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblTramites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpaneCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpaneCursosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpaneCursosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpaneCursosMouseExited(evt);
            }
        });

        jpaneActiveCursos.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpaneActiveCursosLayout = new javax.swing.GroupLayout(jpaneActiveCursos);
        jpaneActiveCursos.setLayout(jpaneActiveCursosLayout);
        jpaneActiveCursosLayout.setHorizontalGroup(
            jpaneActiveCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpaneActiveCursosLayout.setVerticalGroup(
            jpaneActiveCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jlblCursos.setBackground(new java.awt.Color(255, 255, 255));
        jlblCursos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cursos2-materialdesign-35px.png"))); // NOI18N
        jlblCursos.setText("   Mis Cursos");

        javax.swing.GroupLayout jpaneCursosLayout = new javax.swing.GroupLayout(jpaneCursos);
        jpaneCursos.setLayout(jpaneCursosLayout);
        jpaneCursosLayout.setHorizontalGroup(
            jpaneCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneCursosLayout.createSequentialGroup()
                .addComponent(jpaneActiveCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpaneCursosLayout.setVerticalGroup(
            jpaneCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneActiveCursos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpaneSalud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpaneSaludMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpaneSaludMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpaneSaludMouseExited(evt);
            }
        });

        jpaneActiveSalud.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpaneActiveSaludLayout = new javax.swing.GroupLayout(jpaneActiveSalud);
        jpaneActiveSalud.setLayout(jpaneActiveSaludLayout);
        jpaneActiveSaludLayout.setHorizontalGroup(
            jpaneActiveSaludLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jpaneActiveSaludLayout.setVerticalGroup(
            jpaneActiveSaludLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 54, Short.MAX_VALUE)
        );

        jlblSalud.setBackground(new java.awt.Color(255, 255, 255));
        jlblSalud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salud3-materialdesign-35px.png"))); // NOI18N
        jlblSalud.setText("   Mi Salud");

        javax.swing.GroupLayout jpaneSaludLayout = new javax.swing.GroupLayout(jpaneSalud);
        jpaneSalud.setLayout(jpaneSaludLayout);
        jpaneSaludLayout.setHorizontalGroup(
            jpaneSaludLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneSaludLayout.createSequentialGroup()
                .addComponent(jpaneActiveSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpaneSaludLayout.setVerticalGroup(
            jpaneSaludLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneActiveSalud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jlblSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpaneMenuItemsLayout = new javax.swing.GroupLayout(jpaneMenuItems);
        jpaneMenuItems.setLayout(jpaneMenuItemsLayout);
        jpaneMenuItemsLayout.setHorizontalGroup(
            jpaneMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanePerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaneHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaneTramites, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaneCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaneSalud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaneMenuItemsLayout.setVerticalGroup(
            jpaneMenuItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneMenuItemsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanePerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaneHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaneTramites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaneCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpaneSalud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpaneMenuLayout = new javax.swing.GroupLayout(jpaneMenu);
        jpaneMenu.setLayout(jpaneMenuLayout);
        jpaneMenuLayout.setHorizontalGroup(
            jpaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneMenuItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaneMenuLayout.setVerticalGroup(
            jpaneMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneMenuLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jpaneMenuItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpanePrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jscrollpanePaneles.setBackground(new java.awt.Color(255, 255, 255));
        jscrollpanePaneles.setBorder(null);

        javax.swing.GroupLayout jpanePrincipalLayout = new javax.swing.GroupLayout(jpanePrincipal);
        jpanePrincipal.setLayout(jpanePrincipalLayout);
        jpanePrincipalLayout.setHorizontalGroup(
            jpanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrollpanePaneles, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jpanePrincipalLayout.setVerticalGroup(
            jpanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jscrollpanePaneles, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jpaneFondoLayout = new javax.swing.GroupLayout(jpaneFondo);
        jpaneFondo.setLayout(jpaneFondoLayout);
        jpaneFondoLayout.setHorizontalGroup(
            jpaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneFondoLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jpaneMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(730, 833, Short.MAX_VALUE))
            .addComponent(jpanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpaneFondoLayout.setVerticalGroup(
            jpaneFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanePrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpaneMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jpaneMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneMenuMouseEntered
        abrirMenu();
    }//GEN-LAST:event_jpaneMenuMouseEntered

    private void jpaneMenuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneMenuMouseReleased

    }//GEN-LAST:event_jpaneMenuMouseReleased

    private void jpaneMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneMenuMouseExited
        cerrarMenu();
    }//GEN-LAST:event_jpaneMenuMouseExited

    private void jpanePerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanePerfilMouseEntered
        mouseOverItem(jpanePerfil, jpaneActivePerfil, jlblPerfil);
    }//GEN-LAST:event_jpanePerfilMouseEntered

    private void jpanePerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanePerfilMouseExited
        mouseExitedItem(jpanePerfil, jpaneActivePerfil, jlblPerfil);
    }//GEN-LAST:event_jpanePerfilMouseExited

    private void jpaneHorarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneHorarioMouseEntered
        mouseOverItem(jpaneHorario, jpaneActiveHorario, jlblHorario);
    }//GEN-LAST:event_jpaneHorarioMouseEntered

    private void jpaneHorarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneHorarioMouseExited
        mouseExitedItem(jpaneHorario, jpaneActiveHorario, jlblHorario);
    }//GEN-LAST:event_jpaneHorarioMouseExited

    private void jpaneTramitesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneTramitesMouseEntered
        mouseOverItem(jpaneTramites, jpaneActiveTramites, jlblTramites);
    }//GEN-LAST:event_jpaneTramitesMouseEntered

    private void jpaneTramitesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneTramitesMouseExited
        mouseExitedItem(jpaneTramites, jpaneActiveTramites, jlblTramites);
    }//GEN-LAST:event_jpaneTramitesMouseExited

    private void jpaneCursosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneCursosMouseEntered
        mouseOverItem(jpaneCursos, jpaneActiveCursos, jlblCursos);
    }//GEN-LAST:event_jpaneCursosMouseEntered

    private void jpaneCursosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneCursosMouseExited
        mouseExitedItem(jpaneCursos, jpaneActiveCursos, jlblCursos);
    }//GEN-LAST:event_jpaneCursosMouseExited

    private void jpaneSaludMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneSaludMouseEntered
        mouseOverItem(jpaneSalud, jpaneActiveSalud, jlblSalud);
    }//GEN-LAST:event_jpaneSaludMouseEntered

    private void jpaneSaludMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneSaludMouseExited
        mouseExitedItem(jpaneSalud, jpaneActiveSalud, jlblSalud);
    }//GEN-LAST:event_jpaneSaludMouseExited

    private void jpanePerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpanePerfilMouseClicked
        itemClicked(jpanePerfil, jpaneActivePerfil, jlblPerfil, 1);
    }//GEN-LAST:event_jpanePerfilMouseClicked

    private void jpaneHorarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneHorarioMouseClicked
        itemClicked(jpaneHorario, jpaneActiveHorario, jlblHorario, 2);
    }//GEN-LAST:event_jpaneHorarioMouseClicked

    private void jpaneTramitesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneTramitesMouseClicked
        itemClicked(jpaneTramites, jpaneActiveTramites, jlblTramites, 3);
    }//GEN-LAST:event_jpaneTramitesMouseClicked

    private void jpaneCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneCursosMouseClicked
        itemClicked(jpaneCursos, jpaneActiveCursos, jlblCursos, 4);
    }//GEN-LAST:event_jpaneCursosMouseClicked

    private void jpaneSaludMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneSaludMouseClicked
        itemClicked(jpaneSalud, jpaneActiveSalud, jlblSalud, 5);
    }//GEN-LAST:event_jpaneSaludMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblCursos;
    private javax.swing.JLabel jlblHorario;
    private javax.swing.JLabel jlblPerfil;
    private javax.swing.JLabel jlblSalud;
    private javax.swing.JLabel jlblTramites;
    private javax.swing.JPanel jpaneActiveCursos;
    private javax.swing.JPanel jpaneActiveHorario;
    private javax.swing.JPanel jpaneActivePerfil;
    private javax.swing.JPanel jpaneActiveSalud;
    private javax.swing.JPanel jpaneActiveTramites;
    private javax.swing.JPanel jpaneCursos;
    private javax.swing.JPanel jpaneFondo;
    private javax.swing.JPanel jpaneHorario;
    private javax.swing.JPanel jpaneMenu;
    private javax.swing.JPanel jpaneMenuItems;
    private javax.swing.JPanel jpanePerfil;
    private javax.swing.JPanel jpanePrincipal;
    private javax.swing.JPanel jpaneSalud;
    private javax.swing.JPanel jpaneTramites;
    private javax.swing.JScrollPane jscrollpanePaneles;
    // End of variables declaration//GEN-END:variables

    private void codigoInicial() {
        itemPanels = new itemPanel[5];
        itemPanels[0] = new itemPanel(null, null, false);
        itemPanels[1] = new itemPanel(null, null, false);
        itemPanels[2] = new itemPanel(null, null, false);
        itemPanels[3] = new itemPanel(null, null, false);
        itemPanels[4] = new itemPanel(null, null, false);

        setSize(1082, 662);
        jpaneMenu.setBackground(AtributosGUI.color_principal);
        setLocationRelativeTo(null);

        Animacion.Animacion.mover_izquierda(0, 10 - jpaneMenu.getWidth(), 6, 3, jpaneMenu);

        java.awt.Color color_primario = AtributosGUI.color_principal;
        jpanePerfil.setBackground(color_primario);
        jpaneHorario.setBackground(color_primario);
        jpaneCursos.setBackground(color_primario);
        jpaneTramites.setBackground(color_primario);
        jpaneSalud.setBackground(color_primario);
        jpaneMenuItems.setBackground(color_primario);

        jlblCursos.setFont(AtributosGUI.item_label_font);
        jlblHorario.setFont(AtributosGUI.item_label_font);
        jlblPerfil.setFont(AtributosGUI.item_label_font);
        jlblSalud.setFont(AtributosGUI.item_label_font);
        jlblTramites.setFont(AtributosGUI.item_label_font);

        jlblCursos.setForeground(AtributosGUI.item_mouseExited_label_foreground);
        jlblHorario.setForeground(AtributosGUI.item_mouseExited_label_foreground);
        jlblPerfil.setForeground(AtributosGUI.item_mouseExited_label_foreground);
        jlblSalud.setForeground(AtributosGUI.item_mouseExited_label_foreground);
        jlblTramites.setForeground(AtributosGUI.item_mouseExited_label_foreground);

        jpaneActiveCursos.setBackground(AtributosGUI.item_Off_panel_active);
        jpaneActiveHorario.setBackground(AtributosGUI.item_Off_panel_active);
        jpaneActivePerfil.setBackground(AtributosGUI.item_Off_panel_active);
        jpaneActiveSalud.setBackground(AtributosGUI.item_Off_panel_active);
        jpaneActiveTramites.setBackground(AtributosGUI.item_Off_panel_active);

        String espacios = "   ";
        jlblPerfil.setText(espacios + "Mi Perfil");
        jlblHorario.setText(espacios + "Mis Horarios");
        jlblTramites.setText(espacios + "Mis Trámites");
        jlblCursos.setText(espacios + "Mis Cursos");
        jlblSalud.setText(espacios + "Mi Salud");
        
        
    }

    private void abrirMenu() {
        jpaneMenu.grabFocus();
        int pos = jpaneMenu.getX();
        if (pos < -1) {
            Animacion.Animacion.mover_derecha(10 - jpaneMenu.getWidth(), 0, 2, 2, jpaneMenu);
        }
    }

    private void cerrarMenu() {
        int xframe, xmouse;
        xmouse = java.awt.MouseInfo.getPointerInfo().getLocation().x;
        xframe = getX();
        int pos = jpaneMenu.getX();
        if (pos > -1 && (xmouse - xframe) > jpaneMenu.getWidth()) {
            Animacion.Animacion.mover_izquierda(0, 10 - jpaneMenu.getWidth(), 2, 3, jpaneMenu);
        }
    }

    private void mouseOverItem(JPanel pane, JPanel active, JLabel label) {
        mouseOverItem(pane, active, label, null);
    }

    private void mouseOverItem(JPanel pane, JPanel active, JLabel label, String icon) {
        abrirMenu();
        pane.setBackground(AtributosGUI.item_mouseOver_panel);
        if (icon != null) {
            jlblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon)));
        }
    }

    private void mouseExitedItem(JPanel pane, JPanel active, JLabel label) {
        mouseExitedItem(pane, active, label, null);
    }

    private void mouseExitedItem(JPanel pane, JPanel active, JLabel label, String icon) {
        cerrarMenu();
        pane.setBackground(AtributosGUI.color_principal);
        label.setForeground(AtributosGUI.item_mouseExited_label_foreground);
        if (icon != null) {
            jlblPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource(icon)));
        }
    }

    private void nuevohilo() {
        Thread s = new Thread(new Runnable() {
            public void run() {
                int xframe;
                int xmouse;
                while (true) {
                    xframe = getX();
                    xmouse = java.awt.MouseInfo.getPointerInfo().getLocation().x;
                    System.out.println("JFrame x: " + xframe);
                    System.out.println("mouse x:" + xmouse);
                    System.out.println("diferencia: " + (xmouse - xframe));
                    try {
                        Thread.sleep(500);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(PrincipalGUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });
        s.start();
    }

    private void itemClicked(JPanel pane, JPanel active, JLabel label, int item) {
        if (item >= 1 && item <= 5) {
            //esta entre el item 1 y el item 5
            //cerrar menú rapidamente
            //Animacion.Animacion.mover_izquierda(0, 10 - jpaneMenu.getWidth(), 5, 30, jpaneMenu);
            desseleccionarPaneles();
            switch (item) {
                case 1:
                    //Perfil seleccionado
                    if (!itemPanels[item - 1].isOpen()) {
                        itemPanels[item - 1] = new itemPanel(new PanelPerfil(active, this), active, true);
                        System.out.println("nuevo panel creado");
                    }
                    break;
                case 2:
                    //Horario seleccionado
                    if (!itemPanels[item - 1].isOpen()) {
                        itemPanels[item - 1] = new itemPanel(new PanelHorario(active, this), active, true);
                        System.out.println("nuevo panel creado");
                    }
                    break;
                case 3:
                    //Tramites seleccionado
                    if (!itemPanels[item - 1].isOpen()) {
                        itemPanels[item - 1] = new itemPanel(new PanelTramites(pane, active, label, this), active, true);
                        System.out.println("nuevo panel creado");
                    }
                    break;
                case 4:
                    //Cursos seleccionado
                    if (!itemPanels[item - 1].isOpen()) {
                        itemPanels[item - 1] = new itemPanel(new PanelCursos(active, this), active, true);
                        System.out.println("nuevo panel creado");
                    }
                    break;
                case 5:
                    //Salud seleccionado
                    if (!itemPanels[item - 1].isOpen()) {
                        itemPanels[item - 1] = new itemPanel(new PanelSalud(active, this), active, true);
                        System.out.println("nuevo panel creado");
                    }
                    break;
            }
            definirPanel(itemPanels[item - 1].SeleccionarPanel());
            jpaneMenu.updateUI();
            Animacion.Animacion.mover_izquierda(0, 10 - jpaneMenu.getWidth(), 1, 2, jpaneMenu);
        }
    }

    void closeItemPane(JPanel pane, JPanel active, JLabel label, int item) {
        if (item >= 1 && item <= 5) {
            if (itemPanels[item - 1].isOpen()) {
                itemPanels[item - 1] = new itemPanel(null, null, false);
                active.setBackground(AtributosGUI.item_Off_panel_active);
                System.out.println("nuevo panel creado");
            }
            jpaneMenu.updateUI();
            Animacion.Animacion.mover_izquierda(0, 10 - jpaneMenu.getWidth(), 1, 2, jpaneMenu);
        }
    }

    /**
     * Pasará a el estado On (color blanco por defecto) a los ActivePanel's
     */
    private void desseleccionarPaneles() {
        for (itemPanel item : itemPanels) {
            if (item.isOpen()) {
                item.desseleccionarPanel();
            }
        }
    }

    private void definirPanel(JPanel panel) {
        jscrollpanePaneles.setViewportView(panel);
    }

    /**
     * utilizar cuando se cierra algun panel (item)
     */
    public void irAPanelAbierto() {
        //Seleccionar PerfilPanel
        itemClicked(jpanePerfil, jpaneActivePerfil, jlblPerfil, 1);
    }
}
