package complementos;

import java.awt.Color;

/**
 *
 * @author Alisoft
 */
public class jpaneInfoCurso extends javax.swing.JPanel {

    Color color_curso;
    NotasCurso curso;
    
    /**
     * Creates new form jpaneInfoCurso
     * @param curso
     * @param color_curso
     */
    public jpaneInfoCurso(NotasCurso curso, Color color_curso) {
        this.color_curso = color_curso;
        this.curso = curso;
        initComponents();            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtblNotas = new javax.swing.JTable();
        jpaneHeader = new javax.swing.JPanel();
        jlblNombreCurso = new javax.swing.JLabel();
        jlblDescargarSillabus = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlblPromedioAcumulado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlblPuntosParaAprobar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlblInasistencias = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jlblNombreDocente = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jtblNotas.setForeground(new java.awt.Color(51, 51, 51));
        jtblNotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"I",  new Double(14.0),  new Double(14.0),  new Double(15.0),  new Double(14.3)},
                {"II",  new Double(15.0),  new Double(17.0),  new Double(17.0),  new Double(16.4)},
                {"III", null, null, null, null},
                {"IV", null, null, null, null}
            },
            new String [] {
                "Módulo", "EC", "EP", "ED", "PM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblNotas.setSelectionBackground(color_curso);
        jtblNotas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblNotas.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtblNotas);

        jpaneHeader.setBackground(color_curso);

        jlblNombreCurso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlblNombreCurso.setForeground(new java.awt.Color(255, 255, 255));
        jlblNombreCurso.setText(curso.getNombre());

        jlblDescargarSillabus.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jlblDescargarSillabus.setForeground(new java.awt.Color(255, 255, 255));
        jlblDescargarSillabus.setText("Descargar Sillabus");

        javax.swing.GroupLayout jpaneHeaderLayout = new javax.swing.GroupLayout(jpaneHeader);
        jpaneHeader.setLayout(jpaneHeaderLayout);
        jpaneHeaderLayout.setHorizontalGroup(
            jpaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblNombreCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblDescargarSillabus)
                .addGap(16, 16, 16))
        );
        jpaneHeaderLayout.setVerticalGroup(
            jpaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpaneHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpaneHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombreCurso)
                    .addComponent(jlblDescargarSillabus))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Notas:");

        jlblPromedioAcumulado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlblPromedioAcumulado.setForeground(new java.awt.Color(102, 102, 102));
        jlblPromedioAcumulado.setText("15.4");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("P. Acumulado:");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Puntos para aprobar:");

        jlblPuntosParaAprobar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlblPuntosParaAprobar.setForeground(new java.awt.Color(102, 102, 102));
        jlblPuntosParaAprobar.setText("15.4");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Inasistencias:");

        jlblInasistencias.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlblInasistencias.setForeground(new java.awt.Color(102, 102, 102));
        jlblInasistencias.setText("1");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Docente:");

        jlblNombreDocente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jlblNombreDocente.setForeground(new java.awt.Color(102, 102, 102));
        jlblNombreDocente.setText(curso.getDocente());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpaneHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblNombreDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblPromedioAcumulado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlblPuntosParaAprobar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblInasistencias)))
                        .addGap(15, 15, 15))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jpaneHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jlblNombreDocente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jlblPromedioAcumulado)
                    .addComponent(jLabel12)
                    .addComponent(jlblPuntosParaAprobar)
                    .addComponent(jLabel14)
                    .addComponent(jlblInasistencias))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlblDescargarSillabus;
    private javax.swing.JLabel jlblInasistencias;
    private javax.swing.JLabel jlblNombreCurso;
    private javax.swing.JLabel jlblNombreDocente;
    private javax.swing.JLabel jlblPromedioAcumulado;
    private javax.swing.JLabel jlblPuntosParaAprobar;
    private javax.swing.JPanel jpaneHeader;
    private javax.swing.JTable jtblNotas;
    // End of variables declaration//GEN-END:variables
}
